### ISSUE TITLE
您好 想请教一下tvt的那个项目

### ISSUE THREAD

**Issue by daidaishuo** [wood3n/i18n-parser#1]
https://forum.vuejs.org/t/vue/124709
在网上看到了您发的文章，在做vscode 国际化插件的想实现一个功能，想通过解析vue文件 生成 ast 然后讲要所有的标签中的中文文案，包裹上特定的标签例如：<i18n></i18n>, 然后生成一个字符串重新贴回到原来的vue文件。大体思路应该跟您的文章一样，但是文章项目链接失效了，想跟大佬学习一下，大佬可以更新一下链接嘛感谢🙏

**Comment by wood3n** [comment]
> https://forum.vuejs.org/t/vue/124709 在网上看到了您发的文章，在做vscode 国际化插件的想实现一个功能，想通过解析vue文件 生成 ast 然后讲要所有的标签中的中文文案，包裹上特定的标签例如：, 然后生成一个字符串重新贴回到原来的vue文件。大体思路应该跟您的文章一样，但是文章项目链接失效了，想跟大佬学习一下，大佬可以更新一下链接嘛感谢🙏

你好，`tvt` 那个项目我删掉了，代码全部迁移到目前这个仓库了，解析 AST 部分同时替换的代码在这个 package 下面：https://github.com/wood3n/sweet-i18n/tree/master/packages/sugar18
