### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by wangmeijian** [wood3n/i18n-parser#2]
```
// package.json
  "config": {
    "sugar18": {
      "importPath": "@i18n",
      "pattern": "**/*.{vue,js,ts,html}",
    }
  }
// vite.config.js
  resolve: {
    alias: {
      "@i18n": path.resolve(__dirname, "./src"),
    },
  },
```
大佬，这个配置有问题吗？执行trust提示Please set import expression's filepath.   

请指教，盼回复

**Comment by wood3n** [comment]
在`trust`后面加上`-i + [引入的vue-i18n对象的相对路径]`试试，好久没看了，应该是bug 😢 
![image](https://user-images.githubusercontent.com/31716713/236827200-941c75b7-d786-4a82-8a99-e69443c92279.png)
![image](https://user-images.githubusercontent.com/31716713/236827263-b50bd44e-524a-46b4-bbc2-d3f3ea84daf5.png)

**Comment by wangmeijian** [comment]
> 

这里的“引入的vue-i18n对象的相对路径”怎么理解？vue-i18n不是在nodemodule里吗？

**Comment by wangmeijian** [comment]
提了个PR修复了，大佬有空合一下 https://github.com/wood3n/i18n-parser/pull/3

**Comment by wood3n** [comment]
> > 
> 
> 这里的“引入的vue-i18n对象的相对路径”怎么理解？vue-i18n不是在nodemodule里吗？

 `vue-i18n` 用的时候会先初始化一个对象，JS里面语言转换的时候应该需要引用这个对象，`importPath`就是引用这个对象的路径

```js
export const i18n = new VueI18n({
  locale: 'ja', // 设置地区
  messages, // 设置地区信息
})
```

**Comment by wood3n** [comment]
> 提了个PR修复了，大佬有空合一下 #3

谢谢，合了，[1.0.6](https://www.npmjs.com/package/sugar18)

**Comment by wangmeijian** [comment]
这个项目挺好的，需要推广一下😄
